fallout4_utils = {
  "game" : "Fallout 4",
  "utilities" : [
    {
      "_comment_" : ["https://sourceforge.net/projects/modorganizer/",
                     "https://github.com/TanninOne/modorganizer/releases",
					 "https://github.com/LePresidente/modorganizer/releases-https://github.com/LePresidente/modorganizer/releases/download/v2.0.8.3b/Mod.Organizer-2.0.8.3.exe"],
      "name": "Mod Organizer",
      "version": "2.0.7",
      "download": "https://github.com/TanninOne/modorganizer/releases/download/v2.0.7b/Mod.Organizer-2.0.7.exe",
      "sha1": "34d69d98b67c6ebd59088206451fc8422d75a721",
      "install_path": "%FO4Path%\\Mods\\ModOrganizer"
    },
    {
      "_comment_" : "http://f4se.silverlock.org/",
      "name": "SKSE",
      "version": "0.3.0",
      "download": "http://f4se.silverlock.org/beta/f4se_0_03_00.7z",
      "sha1": "2d197c658131d96fe525c651038aff1609cec943",
      "install_path": "%FO4Path%\\MODS"
    },
    {
      "_comment_" : "http://enbdev.com/download_mod_fallout4.htm",
      "name": "ENB",
      "version": "0.311",
      "download": "http://enbdev.com/enbseries_fallout4_v0311.zip",
      "sha1": "98093ad5d03580f869dc79fab3f0f717fad58b82",
      "install_path": "%FO4Path%\\MODS"
    },
	{
      "_comment_" : "http://www.nexusmods.com/fallout4/mods/1822/?",
      "name": "Shadow Boost",
      "version": "1.9.4.0",
      "download": "http://www.dev-c.com/files/ShadowBoost_1.9.4.0.zip",
      "sha1": "14385a3412944d0eea686680566b3f93a44ca077",
      "install_path": "%FO4Path%\\MODS"
    },
	{
      "_comment_" : "https://github.com/loot/loot/releases",
      "name": "LOOT",
      "version": "0.10.3",
      "download": "https://github.com/loot/loot/releases/download/0.10.3/loot_0.10.3-0-g0fcf788_dev_Win32.7z",
      "sha1": "62e2de9277bd98527ba6848f253f89682b3950c8",
      "install_path": "%FO4Path%\\Mods\\LOOT"
    },
    {
      "_comment_" : "https://github.com/TES5Edit",
      "name": "FO4Edit",
      "version": "3.1.3",
      "download": "https://github.com/TES5Edit/TES5Edit/releases/download/FO4Edit-fa3cf0b/FO4Edit.3.1.3.-.fa3cf0b.7z",
      "sha1": "3ba6078c45cf5a9d7d1c0f0f447496aeeac8d49b",
      "install_path": "%FO4Path%\\Mods\\FO4Edit"
    },
    {
      "_comment_" : "https://github.com/matortheeternal/smash/releases",
  		"name": "Mator Smash",
  		"version": "0.4",
  		"download": "https://github.com/matortheeternal/smash/releases/download/0.4/MatorSmash.zip",
      "sha1": "e437683c5a380bc972154d2817758f1fc4ac5053",
  		"install_path": "%FO4Path%\\Mods\\MatorSmash"
  	},
    {
      "_comment_" : "https://github.com/wrye-bash/wrye-bash/releases",
      "name": "Wrye Bash",
      "version": "0.306",
      "download": "https://github.com/wrye-bash/wrye-bash/releases/download/v306/Wrye.Bash.306.-.Standalone.Executable.7z",
      "sha1": "05b373772bee61d8f13a9732950b8036e8daea67",
      "install_path": "%FO4Path%\\Mods\\WryeBash"
    },
	{
	  "_comment_" : "https://github.com/matortheeternal/mod-analyzer/releases",
      "name": "Mod Analyzer",
      "version": "2.0.5",
      "download": "https://github.com/matortheeternal/mod-analyzer/releases/download/2.0.5/ModAnalyzer.zip",
      "sha1": "4f4e3f40a9393a916c451dccc16145ce81e4db23",
      "install_path": "%FO4Path%\\Mods\\ModAnalyzer"
	}
  ],
  "ModOrganizer.ini": {
    "[Plugins]": [
      "Basic%20diagnosis%20plugin\\check_modorder=false"
    ],
    "[customExecutables]": [
      {
        "title": "F4SE",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false",
		"binary": "%FO4Path%\\f4se_loader.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "Fallout 4",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false",
		"binary": "%FO4Path%\\Fallout4.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "Fallout 4 Launcher",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false",
		"binary": "%FO4Path%\\Fallout4Launcher.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "FO4Edit",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%FO4Path%\\Mods\\FO4Edit\\FO4Edit.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "LOOT",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%FO4Path%\\Mods\\LOOT\\LOOT.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "Smash",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%FO4Path%\\Mods\\MatorSmash\\MatorSmash.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "WryeBash",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%FO4Path%\\Mods\\WryeBash\\Wrye Bash.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
	  },
	  {
        "title": "Mod Analyzer",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%FO4Path%\\Mods\\ModAnalyzer\\ModAnalyzer.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
    }
  ]
  }
}
fallout4_99_ids = {	"0" : [None,None, None, None],
	"1" : [None,"X2c - Improved Eyes at Fallout 4 Nexus - Mods and community", "17", "Body, Face, and Hair"],
	"2" : [None,None, None, None],
	"3" : [["Todd.7z-3-.7z"],"Todd Howard Icon for Fallout 4 at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"4" : [None,None, None, None],
	"5" : [["Icon Pack-5-.7z"],"Fallout 4 Icon Pack at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"6" : [None,None, None, None],
	"7" : [["Both Files .ico format (3.0)-7-1-0.7z","Tallhout 4 Icon (God Howard Edition) -7-1-0.7z","Tallhout 4 Icon (God Howard Edition 2.2) -7-1-0.7z"],"\"Toddout 4\" Icon at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"8" : [["GECK Icon-8-1-0.7z","GECK Icon replacer-8-1-0.7z"],"GECK Icon at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"9" : [["CBM - Survival of the Fittest-9-1-1.zip"],"CBM - Survival of the Fittest at Fallout 4 Nexus - Mods and community", "15", "Gameplay Effects and Changes"],
	"10" : [None,None, None, None],
	"11" : [None,None, None, None],
	"12" : [None,None, None, None],
	"13" : [None,None, None, None],
	"14" : [None,None, None, None],
	"15" : [["Caliente's Beautiful Bodies Enhancer - v2.3-15-2-3.7z","CBBE Body and Hands texture Source and Options v1.0-15-1-0.7z","Furry Undergarments Fix-15-1-0.7z","Modder's Resource-15-1-0.7z","CBBE Body and Hands texture Source and Options v1.0-15-1-0.7z"], "Caliente's Beautiful Bodies Enhancer -CBBE", "19", "Models and Textures"],
	"16" : [["Patcher-16-1-9-4.zip"],"Patcher at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"17" : [["T60 Icon-17-FINAL.zip","T60 PNG Version-17-FINAL.zip","T60 PNG-17-FINAL.zip"],"Fallout 4 T60 Icon at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"18" : [None,None, None, None],
	"19" : [None,None, None, None],
	"20" : [None,None, None, None],
	"21" : [None,None, None, None],
	"22" : [None,None, None, None],
	"23" : [None,None, None, None],
	"24" : [None,None, None, None],
	"25" : [["BodySlide and Outfit Studio - v4.2.3-25-4-2-3.7z"],"BodySlide and Outfit Studio at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"26" : [["New Vegas Amber Hud Instructions-26-1.zip","New Vegas Amber Hud Instructions-26-2.zip"],"New Vegas Amber Hud at Fallout 4 Nexus - Mods and community", "37", "User Interface"],
	"27" : [["Time Lapse Main Menu Theme - Long-27-1.zip","Time Lapse Main Menu Theme - Short-27-1.zip"],"Time Lapse Main Menu Replacer at Fallout 4 Nexus - Mods and community", "37", "User Interface"],
	"28" : [None,None, None, None],
	"29" : [None,None, None, None],
	"30" : [None,None, None, None],
	"31" : [["Alternate alternate font 1-31-1.zip","Alternate Alternate Font 2-31-1.zip","Main-31-2.zip","Latin Extended Support Fonts-31-3.zip","Main font only-31-1.zip"],"Alternate UI Fonts at Fallout 4 Nexus - Mods and community", "37", "User Interface"],
	"32" : [["Mutant toad howard-32-1-0.rar"],"Mutant Toad Howard icon at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"33" : [None,None, None, None],
	"34" : [None,None, None, None],
	"35" : [["Fallout 4 Icon - 8k Resolution -35-1-0.7z","Hi-Res Fallout 4 Icon-35-1-0.7z"],"Hi-Res Fallout 4 Icon - 8k at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"36" : [None,None, None, None],
	"37" : [None,None, None, None],
	"38" : [None,None, None, None],
	"39" : [["IcoPack-39-1-8.7z"],"24 AllRez Fallout4 IconSet at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"40" : [["FALLOUT 4 - Enhanced Wasteland Preset v3.0-40-3-0.zip","FALLOUT 4 - Enhanced Wasteland v5.0-40-5-0.zip"],"Enhanced Wasteland Preset at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"41" : [None,None, None, None],
	"42" : [["VOGUE ENB v0.19.1 - COPYRIGHT EDITION-42-v0-19-1.zip","VOGUE ENB v0.19.1 - LITE-42-v0-19-1L.zip","VOGUE ENB v0.19.1 - No DoF Effect-42-v0-19-1n.zip"],"VOGUE ENB - Realism at Fallout 4 Nexus - Mods and community", "13", "ENB Presets"],
	"43" : [["PerkPoster full version.-43-1-0.zip","PerkPoster Patch-43-1-0.zip"],"Unofficial Fallout 4 PerkPoster Patch at Fallout 4 Nexus - Mods and community", "25", "Patches"],
	"44" : [["Godd Howard Icon-44-1-00.zip"],"Godd Howard Icon for Fallout 4 at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"45" : [None,None, None, None],
	"46" : [["The Mod-46-.rar"],"Garage Icon - Custom Photo at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"47" : [None,None, None, None],
	"48" : [None,None, None, None],
	"49" : [None,None, None, None],
	"50" : [None,None, None, None],
	"51" : [["Fo4 icon-51-.rar","Fo4 icon 2-51-.rar"],"Fallout 4 T-60 icons at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"52" : [None,None, None, None],
	"53" : [["Geralt Voice resources-53-1-0.7z","Long version before cuting the lines -53-1-0a.7z"],"Geralt The Witcher Voice Resources at Fallout 4 Nexus - Mods and community", "18", "Modders Resources and Tutorials"],
	"54" : [["Fallout 4 Language Filter-54-0-40.7z"],"Fallout 4 Language Filter at Fallout 4 Nexus - Mods and community", "36", "Audio - Voice"],
	"55" : [None,None, None, None],
	"56" : [None,None, None, None],
	"57" : [None,None, None, None],
	"58" : [["K-putt's_Fallout_ReShade_1.5 'Basic'-58-1-5.rar","K-putt's_Fallout_ReShade_1.5 'Performance'-58-1-5.rar","K-putt's_Fallout_ReShade_1.5 'DOF and AO'-58-.rar"],"K-putt's Config 1.5 at Fallout 4 Nexus - Mods and community", "55", "ReShade Presets"],
	"59" : [None,None, None, None],
	"60" : [None,None, None, None],
	"61" : [["Screenshot Tools-61-.zip"],"Screenshot Tools at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"62" : [["SeamlessPack1-62-1-0.rar","SeamlessPack2-62-1-0.rar","SeamlessPack3-62-1-0.rar"],"Jesters Seamless Texture Pack ( MODDERS RESOURCE ) at Fallout 4 Nexus - Mods and community", "18", "Modders Resources and Tutorials"],
	"63" : [["max-63-2.rar"],"Maxed. S.P.E.C.I.A.L .bat at Fallout 4 Nexus - Mods and community", "8", "Cheats and God items"],
	"64" : [["Settlement Helper-64-1-0.7z","Settlement Helper-64-1-1.7z","Settlement Helper-64-1-2.7z"],"Settlement Helper at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"65" : [None,None, None, None],
	"66" : [["Chris2012 Realistic SweetFX Preset 1.0-66-1-0.rar","Chris2012 Realistic SweetFX Preset 1.1-66-1-1.rar"],"Chris2012's Realistic SweetFX Preset at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"67" : [None,None, None, None],
	"68" : [["Batch File all the junk-68-1-6.rar","Batch File all the ammo-68-1-4.rar"],"Batch File all the junk at Fallout 4 Nexus - Mods and community", "8", "Cheats and God items"],
	"69" : [["Lyssa Vagabond save 1.1-69-1-1.rar","lyssa vagabond after vault -69-.rar"],"Lyssa Vagabond Character at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"70" : [["Vault 111 Quickstart - Female-70-V2.zip","Vault 111 Quickstart - Male-70-V2.zip"],"Vault 111 Quickstart - Male And Female at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"71" : [None,None, None, None],
	"72" : [None,None, None, None],
	"73" : [["ULG 1.2-73-1-2.zip"],"ULG - Ultra Low Graphics for low-end PC's (F4) at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"74" : [None,None, None, None],
	"75" : [None,None, None, None],
	"76" : [None,None, None, None],
	"77" : [["All Items Save-77-1-1-0-0.rar"],"All Items Containers at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"78" : [["BAE v0.10-78-0-10.7z"],"B.A.E. - Bethesda Archive Extractor at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"79" : [["Savegame 1-79-1.rar","Savegame 2-79-1.rar"],"Savegame Female at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"80" : [["The love of Eli-80-1-0.7z"],"The love of Eli - a dystopic Reshade at Fallout 4 Nexus - Mods and community", "55", "ReShade Presets"],
	"81" : [["Backup Files-81-.7z"],"Fallout 4 Config ini at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"82" : [["English Translation-82-0-1.zip","English Translation-82-0-2.zip"],"English Translation at Fallout 4 Nexus - Mods and community", "25", "Patches"],
	"83" : [None,None, None, None],
	"84" : [["Bahuda - Kim - Fallout 4-84-.7z"],"Kim - Face - Character Model at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"85" : [["MoreOrLessXP-85-1-3.zip","Rules for MoreOrLessXP-85-1-3.zip"],"More or Less XP at Fallout 4 Nexus - Mods and community", "2", "Miscellaneous"],
	"86" : [["Stalker Lights 4.0-86-4-0.rar","Stalker Lights 4.1 red error fix-86-4-1.rar","Stalker Lights 4.2 les brightnes-86-4-2.rar"],"Stalker Lights Sweet Fx and ENB at Fallout 4 Nexus - Mods and community", "55", "ReShade Presets"],
	"87" : [["EMMA-87-.rar"],"Crappy Emma Stone at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"88" : [["Experience Points for Level 50-88-1-0.rar"],"Experience Points at Fallout 4 Nexus - Mods and community", "46", "Skills and Leveling"],
	"89" : [["Claire-89-.rar"],"Character Save - Claire at Fallout 4 Nexus - Mods and community", "32", "Saved Games"],
	"90" : [["Ultimate Engine-90-.rar","Ultimate Engine-90-1-3.rar"],"Ultimate Engine at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"91" : [None,None, None, None],
	"92" : [["Fallout 4 Performance Optimization (My Specs)-92-2-0.zip","Fallout 4 Performance Optimization (Weak Shader Compute Cores)-92-1-3.7z","Fallout 4 Performance Optimization - Final-92-1-4.zip","Fallout 4 Performance Optimization Med-Hi Set (Test)-92-1-2.zip","Fallout 4 Performance Optimization Update (Test 3)-92-1-1-3.zip","Fallout 4 Performance Optimization Update (Test Updated)-92-1-1-2.zip","Fallout 4 Performance Optimization-92-1-0.zip"],"Fallout 4 Performance Optimization at Fallout 4 Nexus - Mods and community", "40", "Visuals and Graphics"],
	"93" : [["Guidelines 2015 V5.3.2-93-5-3-2.exe"],"Pyros Software - Guidelines ReadMe and Description Page generator at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"94" : [["Ruined City FX V1.2 (performance)-94-1-2.zip","Ruined City FX V1.2-94-1-2.zip"],"Ruined City FX at Fallout 4 Nexus - Mods and community", "55", "ReShade Presets"],
	"95" : [None,None, None, None],
	"96" : [["2.Power Fan Edition-96-V1-06895.rar","3 Boston Irish Edition-96-V1-04385.rar","4 Rad Sox - Jungle Camo-96-V1-028Camo.rar","5 Rad Sox - Urban Camo-96-V1-09Urb.rar","A. Solid Black-96-V1-05432.rar","B. Jungle Camo-96-V1-048Camo.rar","C. Urban Camo-96-V1-9432.rar","D. Magic Unicorn Rainbows-96-V1-05MURBO.rar","E Vault 111 Standard Issue Panties and Bra-96-V-V111.rar","F. Cow Girl-96-V1-COW.rar","G. Strawberries-96-V1-02Berry.rar","H. SweetHeart Type 1-96-V1-SH1.rar","Immersive Attire Fix-96-V1-09alpha.rar","K. Shinji Swag Edition-96-VShinji.rar","K. SweetHeart Type 2-96-V1-SH2.rar","M.1 Classic Rad Sox for Him (Male)-96-VM-102C.rar","M.2 Black with White Elastic (Ceo Brand Edition) For Him (Male)-96-VBECB.rar","M.3 Magic Rainbow Unicorns for Him (Male)-96-VMUB1.rar","M.A Black with White Elastic for Him (Male)-96-VMBE4.rar","Source Files - PSD V2.01-96-V2-01.rar","SPECIAL Rad Sox Classic Hat Retexture-96-V3-23HAT.rar","zFor Troubleshooting. My Ini files-96-VMyIni.rar"],"Immersive Attire Fix at Fallout 4 Nexus - Mods and community", "19", "Models and Textures"],
	"97" : [["English Strings for Fallout 4 - DEF_UI and FDI Compatibility Version-97-1-9.7z","English Strings for Fallout 4 - DEF_UI Compatibility Version-97-1-9.7z","English Strings for Fallout 4 - Full Dialogue Interface (Paraphrase) Compatibility Version-97-1-9.7z","English Strings for Fallout 4 - Full Dialogue Interface Compatibility Version-97-1-9.7z","English Strings for Fallout 4-97-1-9.7z"],"English Strings for Fallout 4 at Fallout 4 Nexus - Mods and community", "37", "User Interface"],
	"98" : [["f4pexdump.7z-98-1-0.7z"],"F4 Papyrus Dumper at Fallout 4 Nexus - Mods and community", "38", "Utilities"],
	"99" : [["F4R Saved Characters - Caucasian Redhead-99-1-2.rar","F4R Saved Characters - Nora and Nath-99-1-1.rar","F4R Saved Characters-99-1-2.rar"],"Fallout 4 Radioactive - Saved Characters at Fallout 4 Nexus - Mods and community", "32", "Saved Games"]}
fallout4_default_categories_dat = "1|Ammo|3|0\n2|Animation|4|0\n3|Armour|5|0\n4|Audio - Misc|35|0\n5|Audio - Music|34|0\n6|Audio - SFX|33|0\n7|Audio - Voice|36|0\n8|Body, Face, and Hair|17|0\n9|Bug Fixes|6|0\n10|Buildings|7|0\n11|Character Presets|58|0\n12|Cheats and God items|8|0\n13|Clothing|9|0\n14|Clothing - Backpacks|49|0\n15|Collectibles, Treasure Hunts, and Puzzles|10|0\n16|Companions|11|0\n17|Crafting - Equipment|44|0\n18|Crafting - Home/Settlement|45|0\n19|Crafting - Other|50|0\n20|Creatures|12|0\n21|ENB Presets|13|0\n22|Environment|14|0\n23|Factions|16|0\n24|Gameplay Effects and Changes|15|0\n25|Immersion|51|0\n26|Items (Food, Drinks, Chems, etc)|43|0\n27|Locations - New|21|0\n28|Locations - Vanilla|47|0\n29|Miscellaneous|2|0\n30|Modders Resources and Tutorials|18|0\n31|Models and Textures|19|0\n32|New Lands|20|0\n33|NPC|22|0\n34|NPC - Vendors|23|0\n35|Overhauls|24|0\n36|Patches|25|0\n37|Performance|26|0\n38|Perks|27|0\n39|Pip-Boy|52|0\n40|Player Homes|28|0\n41|Player Settlement|48|0\n42|Poses|29|0\n43|Power Armour|53|0\n44|Quests and Adventures|30|0\n45|Radio|31|0\n46|ReShade Presets|55|0\n47|Save Games|32|0\n48|Skills and Leveling|46|0\n49|Tattoos|57|0\n50|User Interface|37|0\n51|Utilities|38|0\n52|Vehicles|39|0\n53|Visuals and Graphics|40|0\n54|Weapons|41|0\n55|Weapons and Armour|42|0\n56|Weather|56|0" #MO2_FO4_categories.dat
skyrim_utils = {
  "game" : "Skyrim",
  "utilities" : [
    {
      "_comment_" : ["https://sourceforge.net/projects/modorganizer/",
                     "https://github.com/TanninOne/modorganizer/releases"],
      "name": "Mod Organizer",
      "version": "1.3.10",
      "download": "http://iweb.dl.sourceforge.net/project/modorganizer/ModOrganizer_v1.3.10.7z",
      "sha1": "a5953ac567f04055ebeb3971916f2ccc107e7172",
      "install_path": "%SkyrimPath%\\Mods\\ModOrganizer"
    },
    {
      "_comment_" : "http://skse.silverlock.org/",
      "name": "SKSE",
      "version": "1.7.3",
      "download": "http://skse.silverlock.org/beta/skse_1_07_03.7z",
      "sha1": "8a0b2a766327103fa25e9b0129647125f7a9a6e6",
      "install_path": "%SkyrimPath%"
    },
    {
      "_comment_" : "http://enbdev.com/download_mod_tesskyrim.html",
      "name": "ENB",
      "version": "0.308",
      "download": "http://enbdev.com/enbseries_skyrim_v0308.zip",
      "sha1": "cec5527abaa285870514377bcc98fe971ed60284",
      "install_path": "%SkyrimPath%"
    },
    {
      "_comment_" : "https://github.com/TES5Edit/TES5Edit/releases",
      "name": "TES5Edit",
      "version": "3.1.2",
      "download": "https://github.com/TES5Edit/TES5Edit/releases/download/xedit-3.1.2/TES5Edit_3_1_2.7z",
      "sha1": "f8db29d2144282156b991b0cb5671d62b0a616cc",
      "install_path": "%SkyrimPath%\\Mods\\TES5Edit"
    },
    {
      "_comment_" : "https://github.com/matortheeternal/smash/releases",
  	  "name": "Mator Smash",
  	  "version": "0.4",
  	  "download": "https://github.com/matortheeternal/smash/releases/download/0.4/MatorSmash.zip",
      "sha1": "e437683c5a380bc972154d2817758f1fc4ac5053",
	  "install_path": "%SkyrimPath%\\Mods\\MatorSmash"
  	},
    {
      "_comment_" : "https://github.com/wrye-bash/wrye-bash/releases",
      "name": "Wrye Bash",
      "version": "0.306",
      "download": "https://github.com/wrye-bash/wrye-bash/releases/download/v306/Wrye.Bash.306.-.Standalone.Executable.7z",
      "sha1": "05b373772bee61d8f13a9732950b8036e8daea67",
      "install_path": "%SkyrimPath%\\Mods\\WryeBash"
    },
	{
	  "_comment_" : "https://github.com/matortheeternal/mod-analyzer/releases",
      "name": "Mod Analyzer",
      "version": "2.0.5",
      "download": "https://github.com/matortheeternal/mod-analyzer/releases/download/2.0.5/ModAnalyzer.zip",
      "sha1": "4f4e3f40a9393a916c451dccc16145ce81e4db23",
      "install_path": "%SkyrimPath%\\Mods\\ModAnalyzer"
	}
  ],
  "ModOrganizer.ini": {
    "[Plugins]": [
      "BSA%20Extractor\\enabled=true",
      "Basic%20diagnosis%20plugin\\check_modorder=false"
    ],
    "[customExecutables]": [
      {
        "title": "SKSE",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false"
      },
      {
        "title": "Skyrim",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false"
      },
      {
        "title": "Skyrim Launcher",
        "custom": "false",
        "toolbar": "false",
        "ownicon": "false"
      },
      {
        "title": "TES5Edit",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%SkyrimPath%\\Mods\\TES5Edit\\TES5Edit.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "LOOT",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%SkyrimPath%\\Mods\\LOOT\\LOOT.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "Smash",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%SkyrimPath%\\Mods\\MatorSmash\\MatorSmash.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
      },
      {
        "title": "WryeBash",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%SkyrimPath%\\Mods\\WryeBash\\Wrye Bash.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
	  },
	  {
        "title": "Mod Analyzer",
        "custom": "true",
        "toolbar": "true",
        "ownicon": "true",
        "binary": "%SkyrimPath%\\Mods\\ModAnalyzer\\ModAnalyzer.exe",
        "arguments": "",
        "workingDirectory": "",
        "closeOnStart": "false",
        "steamAppID": ""
    }
  ]
  }
}
skyrim_99_ids = { "0": [None,None,None,None],
  "1": [None,None,None,None],
  "2": [None,None,None,None],
  "3": [None,None,None,None],
  "4": [None,None,None,None],
  "5": [None,None,None,None],
  "6": [None,None,None,None],
  "7": [None,None,None,None],
  "8": [["1680x1050-8-1.rar"],"Skyrim wallpaper without logo","28","Miscellaneous"],
  "9": [["tes v skyrim quickly wallpaper by hectrol-9-1.rar"],"Hectrol Quickly Wallpaper -1680x1050- -March 1-","28","Miscellaneous"],
  "10": [None,None,None,None],
  "11": [["STEP Vanilla Optimized Textures - Standard-11-1-2.7z","STEP Optimized Vanilla Textures - Performance Version 1.2-11-1-2.7z","Enhanced Distant Terrain v1.1.1-11-1-1-1.7z","The Ruffled Feather v4.4-11-4-4.7z","STEP Compilation Installer - High Res - 2292m-11-2-2-9-2m.7z","STEP Compilation Installer - Normal Res - 2292m-11-2-2-9-2m.7z"],"STEP - Skyrim Total Enhancement Project","79","Overhauls"],
  "12": [["Green eye retexture-12-1.rar"],"Uguublin eye retextures","29","Models and Textures"],
  "13": [["Skyrim Incremental Saver 136-13-1-36.zip"],"Skyrim Incremental Saver","39","Utilities"],
  "14": [None,None,None,None],
  "15": [["Savegame Manager v1_1-15-1-1.zip"],"TES V Savegame Manager","39","Utilities"],
  "16": [None,None,None,None],
  "17": [["CreatePlayer-17-1-0.zip"],"Quick Start","43","Save Games"],
  "18": [["Main File - Caucasian races for now only-18-1-0.zip","Main file - Includes clean hands -18-1-1.zip"],"No Dirty Bodies - Caucasian Female Races","29","Models and Textures"],
  "19": [["Unofficial Skyrim Patch-19-2-1-3b.7z ","SMPC Overwrite Fixes-19-1-0-5.7z"],"Unofficial Skyrim Patch","84","Patches"],
  "20": [None,None,None,None],
  "21": [None,None,None,None],
  "22": [["OTEOYN Skyrim Music Conversion V2-22-2.7z","blah-22-2.7z","StuffOne-22-2.7z","Goo-22-2.7z"],"ON THE EDGE OF YOUR NERVES - Skyrim Music Conversion","61","Audio - SFX, Music, and Voice"],
  "23": [["I Wash ver 93-23-93.zip"],"I Wash -  New Skin for Skyrim","29","Models and Textures"],
  "24": [["Borderless Windowed Fullscreen 1-1-24-1-1.7z"],"Borderless Windowed Fullscreen - AutoHotkey Script","24","Gameplay Effects and Changes"],
  "25": [["New Moons Over Skyrim-25.7z","Deathstar over Skyrim-25-WIP.zip"],"New Moons over Skyrim","29","Models and Textures"],
  "26": [["Detailed_Faces-2_00-26-2-0.7z","Detailed_Faces-2_00-Lite-26-2-0L.zip"],"Detailed Faces v2","29","Models and Textures"],
  "27": [["TruePC Bundle-27-v2-0a.exe","Skyrim-Prefs INI Base-27.zip"],"TruePC by Nekroze","62","Visuals and Graphics"],
  "28": [None,None,None,None],
  "29": [None,None,None,None],
  "30": [["No_More_Blocky_Faces-1_50-30-1-5.7z","Smoothed_Dunmer-1_40-30.7z","Merged_With_LUEF-1_00 -30.7z"],"No More Blocky Faces","29","Models and Textures"],
  "31": [["nvidiaInspector_v1955-31-1.zip"],"Skyrim - NVIDIA Ambient Occlusion","45","Videos and Trailers"],
  "32": [None,None,None,None],
  "33": [["No Kill Moves v1_11-33-1-11.7z"],"No Kill Moves","24","Gameplay Effects and Changes"],
  "34": [["FPS Limiter-34-V1-01.rar"],"FPS Limiter","39","Utilities"],
  "35": [None,None,None,None],
  "36": [["No Blood Splatter on your HUD-36-1-1.zip","No Blood Spurts-36-1-2.zip","No Blood-36-1-3.zip"],"No Blood","62","Visuals and Graphics"],
  "37": [["Imperial Green Outfit-37-1-0.zip"],"Outfits Recolor","29","Models and Textures"],
  "38": [["Nude Females - Barbie Doll-38-1-1.7z"],"Nude Females - Barbie Doll","29","Models and Textures"],
  "39": [["Kaylee EyeShadow Version-39-1-1.rar","Kaylee No EyeShadow Version-39-1-1.rar"],"Kaylee Female Gamesave","43","Save Games"],
  "40": [["Eldothas dunmer savegame-40-1.rar"],"Eldothas Dunmer Male Savefile","43","Save Games"],
  "41": [None,None,None,None],
  "42": [["Optional Red-42-1-0.7z","PSD-42-1.7z","White N Dirty-42-1-2.7z"],"Retextured female underwear","60","Clothing"],
  "43": [["Proper Clean Female Body-43-1-0.zip"],"Proper Clean Female Body","29","Models and Textures"],
  "44": [["SkyrimFemaleMuscleMod-44-1-0.zip","Diesel v1_4 -44-1-4.zip","Female Muscle Mod - DIESEL-44-1-3.zip","FemaleMuscleModv1_1_Chiseled-44.zip","FemaleMuscleModv1_1_Soft-44.zip","FemaleMuscleModv1_2_Chiseled-44.zip","FemaleMuscleModv1_2_Soft-44.zip","4096x4096 v1_5 Diesel-44-1-5.zip","4096x4096 v1_5 Hardcore-44-1-5.zip"],"Female Muscle Mod","29","Models and Textures"],
  "45": [["Obligatory Chainmail Bikini-45-1.zip"],"Obligatory Chainmail Bikini","60","Clothing"],
  "46": [None,None,None,None],
  "47": [["TESV Reduced Texture-47.7z","Readme-47-1-0.7z"],"TESV Reduced Texture Pack","29","Models and Textures"],
  "48": [["fix for ATI AMD video cards-48-1-0.rar"],"framerate fix for ATI cards","62","Visuals and Graphics"],
  "49": [["Slower Skills-49.zip"],"Slower Skill Gain","24","Gameplay Effects and Changes"],
  "50": [["Steel Sword Texture-50-1.zip"],"Alternate Steel Sword Texture","29","Models and Textures"],
  "51": [["Masser Versions-51-2.rar","secunda versions-51-2.rar"],"20 Moons - replacer pack","74","Environmental"],
  "52": [["Max Out All Levels-52.7z","Max Out Perks-52-1-1.7z"],"Max Out All Levels and Perks","39","Utilities"],
  "53": [None,None,None,None],
  "54": [["Small retexture of the Steel Great Sword-54-1.zip","Steel GreatSword Re-Texture gold version-54-1-5.zip"],"Steel GreatSword Re-Texture","29","Models and Textures"],
  "55": [["less dirty female and male faces-55-2-0.zip","less dirty male faces-55-1.zip"],"Less dirty male and female faces","29","Models and Textures"],
  "56": [["start with cheats savegame-56-1.rar"],"start with cheats savegame","43","Save Games"],
  "57": [["steelswordtexture_v1-57-1-0.zip"],"HQ Leather Handle Steel Sword Re-Texture","55","Weapons"],
  "58": [["FemaleSkins-58-1.zip","FemaleSkins_CompressedBodyTextures-58.zip"],"Improved Female Skin Textures","29","Models and Textures"],
  "59": [["Steel War Axe Re-Texture-59-1.zip"],"Steel War Axe Re-texture","29","Models and Textures"],
  "60": [["-Enhanced Blood Textures 3_6c NMM -60-3-6c.7z","Other Blood ESP_tweaks-60-.rar","Old Splatter Textures-60.rar","No Screen Blood-60-1.rar"],"Enhanced Blood Textures","62","Visuals and Graphics"],
  "61": [["Arrow keys lockpicking-61-1.rar"],"Arrow keys Lockpicking","42","User Interface"],
  "62": [["Dragon Texture Pack-62-1-0.zip"],"Improved Dragon Textures","83","Creatures"],
  "63": [None,None,None,None],
  "64": [["Lokir saved game-64-1.rar","Lokir saved game V2-64-2.rar"],"Lokir saved game","43","Save Games"],
  "65": [None,None,None,None],
  "66": [None,"Deutsche Wegweiser","29","Models and Textures"],
  "67": [["Casual Clothing Retexture-67-1.7z"],"Slightly Improved Casual Clothing 01","29","Models and Textures"],
  "68": [None,None,None,None],
  "69": [["SkyRim Creature Alive Version 025CK-69-0-25.7z","SkyRimCreaturesProject-69.7z"],"Skyrim Creatures Alive","79","Overhauls"],
  "70": [["Nude Females - XCE-70.7z","Nude Females v1-5 Photoshop Files-70.7z","Nude Females v1-5-70-1-5.7z"],"Nude Females","29","Models and Textures"],
  "71": [["Twiggys Colourful Barkeeps Textures-71.rar","Optional bouncy mesh-71-1.zip"],"Twiggys Colourful Barkeeps and CHSBHC bouncing meshes","60","Clothing"],
  "72": [["Grey-72-1-0.7z","Ivory-72-1-0.7z","Red-72-1-0.7z","White N Dirty-72-1-1.7z"],"Male underwear retexture","29","Models and Textures"],
  "73": [["Traduction des panneaux avec normal mapping-73-1-2.zip"],"Roadsigns - French translation","29","Models and Textures"],
  "74": [None,None,None,None],
  "75": [["Carine Gamesave-75.rar"],"Carine Female Breton Gamesave","43","Save Games"],
  "76": [["1_4 Beta-76-1-4B.zip","Alchemy Assistant 1_32-Czech Fix-76-1-32.zip"],"Alchemy Assistant","39","Utilities"],
  "77": [["Nude Patch-77-1-0.zip"],"Nude Patch - Women Only","29","Models and Textures"],
  "78": [None,None,None,None],
  "79": [["Underworld vampire eyes-79-1.zip"],"Underworld vampire eyes","29","Models and Textures"],
  "80": [["Alternate Skyrim cursors v1-80.zip","Alternate Skyrim cursors v3-80-3.zip"],"KenMOD - Alternate Skyrim cursors","42","User Interface"],
  "81": [["Imperial Studded Leather Armor-81-1.7z","ImperialChainmailv1-81-1.7z"],"Imperial Chainmail Armor","54","Armour"],
  "82": [["Skyrim-PC-controls-mod2-82-2-0.zip"],"Magic or items left and right hand fix","95","Bug Fixes"],
  "83": [["Carteles en Espanol 2_1-83-2-1.zip","Source PSD-83-1-0.zip"],"Carteles en Espanol -spanish signs-","29","Models and Textures"],
  "84": [["25 kgs x lvl-84-1-01b.rar","500 kgs-84-1-0b.rar"],"25 - 500 kgs x lvl - BETA","24","Gameplay Effects and Changes"],
  "85": [["Enhanced Night Skyrim v04 Aquamarine Galaxy-85-0-4.zip","Enhanced Night Skyrim v04 Blue Galaxy-85-0-4.zip","Enhanced Night Skyrim v04 Color Galaxy-85-0-4.zip","Enhanced Night Skyrim v04 Green Galaxy-85-0-4.zip","Enhanced Night Skyrim v04 High Stars-85-0-4.zip","Enhanced Night Skyrim v04 Low Stars-85-0-4.zip","Enhanced Night Skyrim v04 Lower Stars-85-0-4.zip","Enhanced Night Skyrim v04 Medium Stars-85-0-4.zip"],"Enhanced Night Skyrim","29","Models and Textures"],
  "86": [None,None,None,None],
  "87": [["Commands for Alternate Skills and Perks -CAPS--87-1.zip","Unlock all perks-87-1-0.zip"],"Unlock all perks","40","Cheats and God items"],
  "88": [["Numpad Bindable-88-3-2.zip","Reduced Lockpick-88-3-2.zip"],"Interface Hard Coded Key Tweaks","42","User Interface"],
  "89": [["Respawn rate 1 day-89-1-1.zip","Respawn rate 2 days-89-1-1.zip","Respawn rate 3 days-89-1-1.zip","Respawn rate 4 days-89-1-1.zip","Respawn rate 7 days-89-1-1.zip","SkyrimKeyHelper_2000-88-2-0-0-0.zip","Standard Tweaks-88-3-2.zip"],"Skyrim Respawn","24","Gameplay Effects and Changes"],
  "90": [["hairier texture beta-90-1.rar","hairier texture-90-1.rar"],"Hairier male texture","29","Models and Textures"],
  "91": [None,None,None,None],
  "92": [["Correct-PS3-Button-Icons-1_0-92.zip"],"Correct PS3 Button Icons","42","User Interface"],
  "93": [None,None,None,None],
  "94": [None,None,None,None],
  "95": [["Andalus Font-95-2-0.rar","Centaur - Large-95.rar","Centaur Font-95-2-0.rar","Fertigo Pro Font-95-2-0.rar","Magic Cards Font-95-2-0.rar","Morpheus - Large-95.rar","Morpheus Font-95.rar","Tara Type-95-2-0.rar"],["Fertigo Pro Font-95-2-0.rar"],"Main Font Replacement","42","User Interface"],
  "96": [None,None,None,None],
  "97": [["Green eye recolor high-res-97-.rar"],"Highelf green eye recolor","29","Models and Textures"],
  "98": [["Time on loading v5-98.zip"],"KenMOD - Time on loading screen","42","User Interface"],
  "99": [["Female Clean Face v02-99-0-2.zip","Female Clean Face-99-0-1.zip"],"Human Female Clean Face","29","Models and Textures"]}
skyrim_default_categories_dat = "1|Animations|51|0\n2|Armour|54|0\n3|Sound & Music|61|0\n5|Clothing|60|0\n6|Collectables|92|0\n28|Companions|66,96|0\n7|Creatures & Mounts|83,65|0\n8|Factions|25|0\n9|Gameplay|24|0\n10|Hair|26|0\n11|Items|27,85|0\n32|Mercantile|69|0\n19|Weapons|55|11\n36|Weapon & Armour Sets|39|11\n12|Locations|22,30,70,88,89,90,91|0\n31|Landscape Changes|58|0\n4|Cities|53|12\n29|Environment|74|0\n30|Immersion|78|0\n25|Castles & Mansions|68|23\n20|Magic|75,93,94|0\n21|Models & Textures|29|0\n33|Modders resources|82|0\n13|NPCs|33|0\n14|Patches|79,84|0\n24|Bugfixes|95|0\n35|Utilities|38,39|0\n26|Cheats|40|0\n23|Player Homes|67|0\n15|Quests|35|0\n16|Races & Classes|34|0\n27|Combat|77|0\n22|Skills|73|0\n34|Stealth|76|0\n17|UI|42|0\n18|Visuals|62|0" #MO_default_categories.dat
